=== p2pdops/WPLab/week5/dtd/students.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student+)>
<!ELEMENT student (roll,name,dep)>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT dep (#PCDATA)>
<!ATTLIST student id CDATA #REQUIRED>

=== p2pdops/WPLab/week5/dtd/students_external.xml
<?xml version="1.0"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
    <student id="1">
        <roll>19131A1204</roll>
        <name>Surya</name>
        <dep>IT</dep>
    </student>
    <student id="2">
        <roll>19131A1204</roll>
        <name>Chandra</name>
        <dep>IT</dep>
    </student>
    <student id="3">
        <roll>19131A1204</roll>
        <name>Pavan</name>
        <dep>IT</dep>
    </student>
</students>
